plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-internal_affairs

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/rubocop-sidekiq.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/ExampleLength:
  CountAsOne:
    - heredoc
  Max: 11

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
